/* eslint-disable @next/next/no-sync-scripts */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Topbar from "./components/Topbar";
import Sidebar from "./components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={`${inter.className} flex flex-col`}>
          <Topbar />
          <div className="flex flex-1 pt-16">
            <Sidebar />
            <div className="flex-1 p-4 overflow-y-auto">{children}</div>
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
